version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis
      - POSTGRES_CONFIGURATION_ENVIRONMENT=dockerCompose
  redis:
    image: "redis"
    ports:
      - "6379:6379"
  postgres:
    build: ./postgres/.
    ports:
      - "5432:5432"


